set nocompatible			"disable old vi bugs



colorscheme slate
"colorscheme delek
"colorscheme elflord

"""UTF-8 encoding
set enc=utf-8
set fenc=utf-8
set termencoding=utf-8

"""turn off modelines (don't use vim specific commands per file)
set modelines=0

"""basic QOL
syntax enable
"set visualbell				"blink cursor instead of sounding
set history=100
set undolevels=100
set number 					"show line numbers
set scrolloff=3				"scroll before edge of screen
filetype plugin indent on
set autoindent				"automatically indent
set smartindent				"be C aware when auto intenting
set showmatch				"hilight matching brace
set comments=sl:/*,mb:\ *,elx:\ */
set path+=**				"fuzzy file search
set laststatus=2

"""improve status line
set statusline=
set statusline+=%f			"tail of filename
set statusline+=[%n%H%M%R%W]	"Display what buffer, if it is help, if modified, if read only, and if preview
set statusline+=[%{strlen(&fenc)?&fenc:'none'},	"file encoding
set statusline+=%{&ff}]		"file format
set statusline+=%y			"filetype
set statusline+=%=			"left/right separator
set statusline+=[%b]\ 	"value of character under cursor
set statusline+=%c\ 			"cursor column
set statusline+=%l/%L		"cursor line/total lines
set statusline+=\ %P		"percentage through file

"""tab stuff
set tabstop=4
set expandtab
set shiftwidth=4
set autoindent

"""use a mouse
""if has('mouse')
""	set mouse=a
""endif

"""searching
set incsearch
set hlsearch

"""helpfulness
set showcmd					"show cmd as we type
set cursorline				"hilight the current line
set wildmenu				"menu when tab complete
set wildignore=*.swp,*.bak,*.o,.git/*,*.a,*.so,build/*
"set lazyredraw	"don't reraw during macros

"""custom commands
"insert custom banner (i.e. UNCLASSIFIED)
"command Banner :r ~/Banner.txt
"map <F4> :Banner<CR>

"clear search
map <C-l> :noh<CR>

"build project
command CMake !mkdir -p build && cd build && cmake .. && make -j8
map <F5> :CMake<CR>

"clean project
command GitClean !git clean -dfX
map <C-F5> :GitClean<CR>

"save progress
command GitAdd !git add .
map <C-s> :wa<CR>:GitAdd<CR>

"use ctrl+F12 to generate tags for the current project
map <C-F12> :!ctags -R --sort=yes --c++-kinds=+p --fields=+iaS -f ~/.vim/tags/project --extra=+q .<CR>
set tags+=~/.vim/tags/project


set backupdir=$HOME/.vim/backups//
set directory=$HOME/.vim/swapfiles//

"""plugins
set nocp
filetype plugin on

call plug#begin()
Plug 'preservim/NERDTree'
Plug 'derekwyatt/vim-fswitch'
Plug 'cofyc/vim-uncrustify'
Plug 'vim-scripts/DoxygenToolkit.vim'
"Plug 'prabirshrestha/vim-lsp'
"Plug 'mattn/vim-lsp-settings'
Plug 'vim-scripts/OmniCppComplete'
Plug 'junegunn/fzf' 
Plug 'junegunn/fzf.vim'
"Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'yegappan/taglist'
call plug#end()


"""""OmniCpp
"" get std headers
" cp -R /usr/include/c++/$GCC_VERSION ~/.vim/cpp_src
" # it is not necessary to rename headers without an extension
" # replace the 'namespace std _GLIBCXX_VISIBILITY(default)' with 'namespace std'
" find . -type f | xargs sed -i 's/namespace std _GLIBCXX_VISIBILITY(default)/namespace std/'
" ctags -f cpp_tags -R --c++-kinds=+p --fields=+iaS --extra=+q --language-force=C++ -I _GLIBCXX_NOEXCEPT cpp_src
set tags+=~/.vim/tags/cpp
set tags+=~/.vim/tags/cpp_tags
let OmniCpp_NamespaceSearch = 1
let OmniCpp_GlobalScopeSearch = 1
let OmniCpp_ShowAccess = 1
let OmniCpp_ShowPrototypeInAbbr = 1
let OmniCpp_MayCompleteDot = 1
let OmniCpp_MayCompleteArrow = 1
let OmniCpp_MayCompleteScope = 1
let OmniCpp_DefaultNamespaces = ["std", "_GLIBCXX_STD"]
au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
set completeopt=menuone,menu,longest,preview

"""""NERDTree
"autocmd vimenter * NERDTree		"start NERDTree when vim starts with a file
map <C-a> :NERDTreeToggle<CR>

"start NERDTree when vim starts without a file
autocmd vimenter StdinReadPre * let s:std_in=1
autocmd vimenter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

function! NERDTreeHighlightFile(extension, fg, bg, guifg, guibg)
	exec 'autocmd FileType nerdtree highlight ' . a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg .' guibg='. a:guibg .' guifg='. a:guifg
	exec 'autocmd FileType nerdtree syn match ' . a:extension .' #^\s\+.*'. a:extension .'$#'
endfunction

call NERDTreeHighlightFile('cpp', 'green', 'none', 'green', '#151515')
call NERDTreeHighlightFile('h', 'darkgreen', 'none', 'darkgreen', '#151515')
call NERDTreeHighlightFile('c', 'red', 'none', 'red', '#151515')

call NERDTreeHighlightFile('txt', 'yellow', 'none', 'yellow', '#151515')

let NERDTreeIgnore = ['\CMakeFiles$', '\CMakeCache.txt$', '\~$', '\.a$']

"""""uncrustify
function! FindUncrustifyFile()
    let g:uncrustify_cfg_file_path = system("ls -1 | grep cfg | head -n 1")[:-2]
endfunction

autocmd FileType c noremap <buffer> <S-f> :call FindUncrustifyFile() <bar> :call Uncrustify('c')<CR>
autocmd FileType c vnoremap <buffer> <S-f> :call FindUncrustifyFile() <bar> :call RangeUncrustify('c')<CR>
autocmd FileType cpp noremap <buffer> <S-f> :call FindUncrustifyFile() <bar> :call Uncrustify('cpp')<CR>
autocmd FileType cpp vnoremap <buffer> <S-f> :call FindUncrustifyFile() <bar> :call RangeUncrustify('cpp')<CR>

"""""doxygen
let g:DoxygenToolkit_briefTag_pre="\\brief "
let g:DoxygenToolkit_paramTag_pre="\\param "
let g:DoxygenToolkit_returnTag="\\return "

map <c-F9> :Dox<CR>


"""""fswitch
""set rtp+=~/.vim/plugins/fswitch

map <F4> :FSHere<CR>

""""fzf
map <C-f> :GFiles<CR>

" [Buffers] Jump to the existing window if possible
let g:fzf_buffers_jump = 1

" [Tags] Command to generate tags file
let g:fzf_tags_command = 'ctags -R'

" [Commands] --expect expression for directly executing the command
let g:fzf_commands_expect = 'alt-enter,ctrl-x'

"""" taglist
nnoremap <silent> <F8> :TlistToggle<CR>
let Tlist_Exit_OnlyWindow = 1
let Tlist_Use_Right_Window = 1
let Tlist_WinWidth = 45
let Tlist_Display_Prototype = 1

nnoremap <silent> <c-F7> :TlistAddFilesRecursive src *.cpp<CR> :TlistAddFilesRecursive include *.h<CR>
nnoremap <silent> <F7> :TlistUpdate<CR>


